/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    selectOrMove
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_Main_selectOrMove
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Main
 * Method:    getValidMoves
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_Main_getValidMoves
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Main
 * Method:    getPiece
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Main_getPiece
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Main
 * Method:    getCurrentPlayer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Main_getCurrentPlayer
  (JNIEnv *, jobject);

/*
 * Class:     Main
 * Method:    getScorePlayer1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Main_getScorePlayer1
  (JNIEnv *, jobject);

/*
 * Class:     Main
 * Method:    getScorePlayer2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Main_getScorePlayer2
  (JNIEnv *, jobject);

/*
 * Class:     Main
 * Method:    getCheckerboard
 * Signature: ()[[I
 */
JNIEXPORT jobjectArray JNICALL Java_Main_getCheckerboard
  (JNIEnv *, jobject);

/*
 * Class:     Main
 * Method:    resetGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Main_resetGame
  (JNIEnv *, jobject);

/*
 * Class:     Main
 * Method:    setPlayerScore
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Main_setPlayerScore
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
